version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - tradeapp_network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/var/lib/mongodb/data/
    env_file:
      - .env
    networks:
      - tradeapp_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - '2181:2181'
    networks:
      - tradeapp_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
      - '9092:9092'
    networks:
      - tradeapp_network
    env_file:
      - .env

  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - '9000:9000'
    env_file:
      - .env
    networks:
      - tradeapp_network


networks:
  tradeapp_network:
    external: True


volumes:
  mongodb_data:
